filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log
    fields_under_root: true
    fields:
      log_from: nginx-filebeat

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "nginx-access-filebeat-%{+yyyy.MM.dd}"
setup.ilm.enabled: false
setup.template.enabled: false
